# Generated by Django 3.2.9 on 2021-12-22 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item_image',
            field=models.ImageField(upload_to='static/img/auction_imgs', verbose_name='Item Image'),
        ),
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('rate_date', models.DateTimeField(auto_now_add=True, verbose_name='Rate Date')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='auction.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'ordering': ['-rate_date'],
            },
        ),
    ]
