# Generated by Django 3.2.9 on 2021-12-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='item_condution',
            field=models.TextField(default='empty', verbose_name='Item Condution Details'),
            preserve_default=False,
        ),
    ]
