# Generated by Django 3.2.9 on 2021-12-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_item_condution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='auction_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='auction_seller',
            new_name='user',
        ),
    ]
