# Generated by Django 3.2.9 on 2021-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='annennnasil', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
