# Generated by Django 3.2.9 on 2021-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item_image',
            field=models.ImageField(blank=True, default='static/img/profile_pics/default.png', upload_to='static/img/auction_imgs', verbose_name='Item Image'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bid Amount'),
        ),
    ]
