# Generated by Django 3.2.9 on 2021-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active_auction_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Active Auction Count'),
        ),
        migrations.AddField(
            model_name='category',
            name='auction_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Auction Count'),
        ),
    ]
