# Generated by Django 4.0 on 2021-12-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_comment_auction_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
