# Generated by Django 4.0 on 2021-12-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auction', '0007_remove_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('auction', 'auction_report'), ('user', 'user_report'), ('comment', 'comment_report')], default='auction', max_length=30)),
                ('auction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auction.comment')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='auth.user')),
            ],
        ),
    ]
