# Generated by Django 3.2.9 on 2021-12-05 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0007_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auth.user'),
            preserve_default=False,
        ),
    ]
