# Generated by Django 3.2.9 on 2021-12-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('hidden', 'hidden_bid'), ('shown', 'shown_bid')], default='shown', max_length=10, verbose_name='Auction Type'),
        ),
        migrations.AddField(
            model_name='auction',
            name='initializing_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Auction Initializing Bid'),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Auction Active'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(verbose_name='Auction Description'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(verbose_name='Auction End Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(upload_to='auction/images/', verbose_name='Auction Image'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Auction Name'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Auction Name'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(verbose_name='Auction Start Date'),
        ),
    ]
