# Generated by Django 3.2.9 on 2021-12-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20211207_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('hidden', 'hidden_bid'), ('shown', 'shown_bid')], default='shown', max_length=10),
        ),
    ]
