# Generated by Django 3.2.9 on 2021-12-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_auction_auction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Auction Slug'),
        ),
    ]
