# Generated by Django 3.2.9 on 2021-12-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_auction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(upload_to='static/img/auction_imgs', verbose_name='Auction Image'),
        ),
    ]
