# Generated by Django 3.2.9 on 2021-12-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_rate_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_rate_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_rate_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_rate_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_rate_5',
            field=models.IntegerField(default=1),
        ),
    ]
