# Generated by Django 3.2.9 on 2021-12-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211202_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_tc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='tc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
