# Generated by Django 3.2.9 on 2021-12-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fullName',
        ),
    ]
